"""second

Revision ID: 6db0e8d95f0a
Revises: 73761e647914
Create Date: 2022-09-16 22:18:26.002383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db0e8d95f0a'
down_revision = '73761e647914'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
