"""init

Revision ID: d983a262a9e9
Revises: 997dcc2f18de
Create Date: 2022-08-09 14:18:45.489683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd983a262a9e9'
down_revision = '997dcc2f18de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
